---
- name: "Wait for connection..."
  wait_for_connection:
    timeout: 300

- name: Assert that "openvpn_server_ip" is set, not empty, and a valid IP address
  assert:
    that:
      - openvpn_server_ip is defined
      - openvpn_server_ip | length > 0
      - openvpn_server_ip | regex_search('^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$') is not none  # Check for valid IPv4 format
      - openvpn_server_ip.split('.') | map('int') | select('>=', 0) | list | length == 4  # Validate octets are integers
      - openvpn_server_ip.split('.') | map('int') | select('<=', 255) | list | length == 4 # Ensure octets are <= 255

- name: Assert that "openvpn_client_bundle_copy_locally.client_dir" is set, is not empty and ends with "/"
  assert:
    that:
      - openvpn_client_bundle_copy_locally.client_dir is defined
      - openvpn_client_bundle_copy_locally.client_dir | length > 0
      - openvpn_client_bundle_copy_locally.client_dir.endswith('/')

- name: Including Openvpn setup tasks
  include_tasks: "openvpn.yml"
